name: Build macOS

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: pip install pyinstaller pygame

      - name: Compiler
        run: |
          pyinstaller --onefile --windowed \
            --add-data "assets:assets" \
            --name "FlappyBirdMac" main.py

      - name: Créer le DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "FlappyBird" \
            --window-size 500 300 \
            --icon-size 100 \
            --app-drop-link 380 150 \
            "FlappyBird.dmg" \
            "dist/"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: FlappyBirdMac-dmg
          path: FlappyBird.dmg